name: Tests

on:
  push:
    branches:
      - 'master'
  pull_request:

jobs:
  eslint:
    name: ESLint check
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: install node v13
      uses: actions/setup-node@v1
      with:
        node-version: 13
    - name: Install eslint and dependencies
      run: npm install typescript eslint jsonlint-mod @typescript-eslint/parser @typescript-eslint/eslint-plugin --only=dev
    - name: Run eslint
      run: make eslint
    - name: Run jsonlint
      run: make jsonlint
  nedb:
    name: NeDB tests
    needs: eslint
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: install node v13
      if: contains(github.event.body, '[skip-tests]') != true && contains(github.event.body, '[skip-test]') != true
      uses: actions/setup-node@v1
      with:
        node-version: 13
    - name: Install all dependencies
      if: contains(github.event.body, '[skip-tests]') != true && contains(github.event.body, '[skip-test]') != true
      run: make
    - name: Set proper db to use
      if: contains(github.event.body, '[skip-tests]') != true && contains(github.event.body, '[skip-test]') != true
      run: npm run test:config:nedb
    - name: Run mocha
      if: contains(github.event.body, '[skip-tests]') != true && contains(github.event.body, '[skip-test]') != true
      run: npm test
  mongodb:
    name: MongoDB tests
    needs: eslint
    services:
      mongodb:
        image: mongo
        ports:
          - 27017:27017
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: install node v13
      if: contains(github.event.body, '[skip-tests]') != true && contains(github.event.body, '[skip-test]') != true
      uses: actions/setup-node@v1
      with:
        node-version: 12
    - name: Install all dependencies
      if: contains(github.event.body, '[skip-tests]') != true && contains(github.event.body, '[skip-test]') != true
      run: make
    - name: Set proper db to use
      if: contains(github.event.body, '[skip-tests]') != true && contains(github.event.body, '[skip-test]') != true
      run: npm run test:config:mongodb
    - name: Run mocha
      if: contains(github.event.body, '[skip-tests]') != true && contains(github.event.body, '[skip-test]') != true
      run: npm test