on:
  push:

jobs:
  eslint:
    name: ESLint check
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: install node v12
      uses: actions/setup-node@v1
      with:
        node-version: 12
    - name: Install eslint and dependencies
      run: npm install typescript eslint @typescript-eslint/parser @typescript-eslint/eslint-plugin --only=dev
    - name: Run eslint
      run: npx eslint --ext .ts src --quiet
  nedb:
    name: NeDB tests
    needs: eslint
    runs-on: ubuntu-latest
    if: contains(github.event.commits[0].message, '[skip-tests]') != true && contains(github.event.commits[0].message, '[skip-test]') != true
    steps:
    - uses: actions/checkout@master
    - name: install node v12
      uses: actions/setup-node@v1
    - name: Install all dependencies
      run: make
    - name: Set proper db to use
      run: npm run test:config:nedb
    - name: Run mocha
      run: npm test
  mongodb:
    name: MongoDB tests
    needs: eslint
    services:
      mongodb:
        image: mongo
        ports:
          - 27017:27017
    runs-on: ubuntu-latest
    if: contains(github.event.commits[0].message, '[skip-tests]') != true && contains(github.event.commits[0].message, '[skip-test]') != true
    steps:
    - uses: actions/checkout@master
    - name: install node v12
      uses: actions/setup-node@v1
    - name: Install all dependencies
      run: make
    - name: Set proper db to use
      run: npm run test:config:mongodb
    - name: Run mocha
      run: npm test